CREATE TABLE player_stats (
    index SERIAL PRIMARY KEY,
    Rank CHAR(50),
    Season_Game CHAR(50),
    Date DATE,
    Age CHAR(50),
    Team CHAR(50),
    "Unnamed: 5" CHAR(50),
    Opponent CHAR(50),
    difference CHAR(50), -- Renaming "Unnamed: 7" to "difference"
    Games_Started CHAR(50),
    Minutes_Played CHAR(50),
    Field_Goals CHAR(50),
    Field_Goal_Attempts CHAR(50),
    Field_Goal_Percentage CHAR(50),
    Three_Point_Field_Goals CHAR(50),
    Three_Point_Field_Goal_Attempts CHAR(50),
    Three_Point_Field_Goal_Percentage CHAR(50),
    Free_Throws CHAR(50),
    Free_Throw_Attempts CHAR(50),
    Free_Throw_Percentage CHAR(50),
    Offensive_Rebounds CHAR(50),
    Defensive_Rebounds CHAR(50),
    Total_Rebounds CHAR(50),
    Assists CHAR(50),
    Steals CHAR(50),
    Blocks CHAR(50),
    Turnovers CHAR(50),
    Personal_Fouls CHAR(50),
    Points CHAR(50),
    Game_Score CHAR(50),
    Plus_Minus CHAR(50)
);
