CREATE TABLE clean_table AS
SELECT
    index,
    Rank,
    Season_Game,
    Date,
    Age,
    Team,
    Opponent,
    difference,
    CAST(Games_Started AS numeric) AS Games_Started,
    CAST(Field_Goals AS numeric) AS Field_Goals,
    CAST(Field_Goal_Attempts AS numeric) AS Field_Goal_Attempts,
    CAST(Field_Goal_Percentage AS numeric) AS Field_Goal_Percentage,
    CAST(Three_Point_Field_Goals AS numeric) AS Three_Point_Field_Goals,
    CAST(Three_Point_Field_Goal_Attempts AS numeric) AS Three_Point_Field_Goal_Attempts,
    CAST(Three_Point_Field_Goal_Percentage AS numeric) AS Three_Point_Field_Goal_Percentage,
    CAST(Free_Throws AS numeric) AS Free_Throws,
    CAST(Free_Throw_Attempts AS numeric) AS Free_Throw_Attempts,
    CAST(Free_Throw_Percentage AS numeric) AS Free_Throw_Percentage,
    CAST(Offensive_Rebounds AS numeric) AS Offensive_Rebounds,
    CAST(Defensive_Rebounds AS numeric) AS Defensive_Rebounds,
    CAST(Total_Rebounds AS numeric) AS Total_Rebounds,
    CAST(Assists AS numeric) AS Assists,
    CAST(Steals AS numeric) AS Steals,
    CAST(Blocks AS numeric) AS Blocks,
    CAST(Turnovers AS numeric) AS Turnovers,
    CAST(Personal_Fouls AS numeric) AS Personal_Fouls,
    CAST(Points AS numeric) AS Points,
    CAST(Game_Score AS numeric) AS Game_Score,
    CAST(Plus_Minus AS numeric) AS Plus_Minus
FROM clean_combined_data;
